#!/usr/bin/env bash

function krew_install() {
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
  echo "export PATH=\"${KREW_ROOT:-$HOME/.krew}/bin:$PATH\"" >> ~/.zshrc
}

# Make sure to install zsh, oh-my-zsh and p10k before continuing
function zsh_init() {
  [ zsh --version ] || {
    echo "Installing zsh"
    sudo apt install -y zsh
  }
  [ oh-my-zsh --version ] || {
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  }
  [ p10k --version ] || {
    echo "Installing p10k"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  }
}

[ $(uname) = "Linux" ] && apt update && export PKGMGR=apt
[ $(uname) = "Darwin" ]] && {
  xcode-select --install
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  export PKGMGR=brew
}

declare -a packages=(
  1password-cli
  awscli
  bat
  cmake
  compdef
  fluxcd/tap/flux
  fzf
  golang
  jq
  k9s
  kubernetes-cli
  kubectx
  most
  neovim
  npm
  pipx
  pyenv
  ripgrep
  stern
  tfenv
  thefuck
  tmux
  tree
  wget
  yq
  zed
)

if [ -z "${PKGMGR}" ]; then
  echo "Unsupported OS. Please install Homebrew or apt."
  exit 1
elif [ "${PKGMGR}" = "apt" ]; then
  sudo "${PKGMGR}" install -y --no-install-recommends "${packages[@]}" || {
    echo "Failed to install some packages with ${PKGMGR}."
  }
elif [ "${PKGMGR}" = "brew" ]; then
  ${PKGMGR} install "${packages[@]}" || {
    echo "Failed to install some packages with ${PKGMGR}."
  }
fi

declare -a pipx_installs=(
  pre-commit
  pygments
  detect-secrets
)
[ pipx --version ] && pipx install "${pipx_installs[@]}"

declare -a npm_packages=(
  "@google/gemini-cli"
)

for npm_package in "${npm_packages[@]}"; do
  npm install -g "${npm_package}"
done

declare -a krew_packages=(
  crd-wizard
  datadog
  debug-shell
  get-all
  secretdata
  tmux-exec
  wild
)

for krew_package in "${krew_packages[@]}"; do
  krew install "${krew_package}"
done

if [ -d "/workspaces/${DEVPOD_WORKSPACE_ID}" ]; then
  cd "/workspaces/${DEVPOD_WORKSPACE_ID}" || exit
  echo "Detected Codespaces or Devpod environment."
  echo "Ensuring workspace id ${DEVPOD_WORKSPACE_ID} is protected by detect-secrets and pre-commit."
  [ -f "/workspaces/${DEVPOD_WORKSPACE_ID}/.pre-commit-config.yaml" ] || { \
    cp /home/${USER}/dotfiles/.pre-commit-config.yaml /workspaces/${DEVPOD_WORKSPACE_NAME} || \
    echo "No precommit config found in dotfiles." && \
    pre-commit autoupdate && pre-commit install --install-hooks
  }
  [ -f "/workspaces/${DEVPOD_WORKSPACE_ID}/.secrets.baseline" ] || \
    detect-secrets scan --all-files > /workspaces/${DEVPOD_WORKSPACE_NAME}/.secrets.baseline

declare -a dotfiles=(
  .gitconfig
  .oh-my-zsh
  .p10k.zsh
  .terraformrc
  .tmux.conf
  .zshrc
)

for df in "$dotfiles[@]"; do
  echo "Copying dotfile/dotdir ${df}"
  cp -r "dotfiles/${df}" "${HOME}/" || echo "Either ${df} not found in dotfiles or copy failed."
done

source "${HOME}/.zshrc"

echo "Copying nvim config"
mkdir -p "${HOME}/.config/"
[ -d "./nvim" ] && cp -r ./nvim ${HOME}/.config/
