return {}
--
-- return {
--   "kevinhwang91/nvim-ufo",
-- 	lazy = true,
-- 	event = 'VeryLazy',
-- 	keys = {
-- 		{
-- 			"<leader>zo",
-- 			function()
-- 				ufo.openAllFolds()
-- 			end,
-- 		},
-- 		{
-- 			"<leader>zc",
-- 			function()
-- 				require("ufo").closeAllFolds()
-- 			end,
-- 		},
-- 	},
-- 	dependencies = {
-- 		"kevinhwang91/promise-async",
-- 		{
-- 			"luukvbaal/statuscol.nvim",
-- 			config = function()
-- 				local builtin = require("statuscol.builtin")
-- 				require("statuscol").setup({
-- 					-- foldfunc = "builtin",
-- 					-- setopt = true,
-- 					relculright = true,
-- 					segments = {
-- 						{ text = { builtin.foldfunc }, click = "v:lua.ScFa" },
-- 						{ text = { "%s" }, click = "v:lua.ScSa" },
-- 						{ text = { builtin.lnumfunc, " " }, click = "v:lua.ScLa" },
-- 					},
-- 				})
-- 			end,
-- 		},
-- 		{ "chrisgrieser/nvim-origami", opts = true, lazy = true },
-- 	},
--   config = function()
--     require('ufo').setup ({
--       {import = 'editor.ufo'},
--     })
--   end
-- }
